name: sshping
base: core24
version: '0.1'
summary: "Measure character-echo latency and bandwidth for an interactive ssh session"
description: |
  Use this utility to test the performance of interactive ssh sessions or scp file transfers.
  It uses ssh to log into a remote system, then runs two tests: the first test sends one character at a time, waiting for each character to be returned while it records the latency time for each.
  The second test sends a dummy file over scp to /dev/null on the remote system.

  For the echo test, you may specify a character count limit (-c) or a test time limit (-t), and also the command (-e) used on the remote system that echoes characters back.

  For the speed test, you may specify the number of megabytes to send (-s) and the target location for the copies (-z).

  The default output format is RFC-2822 compliant with simple integers so parsing is easy.
  You may also display delimiters to make reading of large numbers easier, or you may use a "human readable" format that displays values using SI prefixes to keep the numberic value small.

  # SSH Keys Interface

  By default, the snap interface for SSH keys is not connected.
  In order to use SSH keys with this snap, you will need to connect the `ssh-keys` interface manually.
  You can do this after installation by running:

  ```bash
  snap connect sshping:ssh-keys
  ```

  This is a third-party snap, not officially supported by the original author..
  Find the original source code at https://github.com/spook/sshping

grade: stable
confinement: strict
license: MIT
contact: https://github.com/alexdlukens/sshping
source-code: https://github.com/spook/sshping

type: app

parts:
  sshping:
    # See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/spook/sshping.git
    source-type: git
    build-packages:
      - gcc
      - g++
      - libssh-dev
      - make
    stage-packages:
      - libssh-4
    override-build: |
      make sshping
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp bin/sshping $SNAPCRAFT_PART_INSTALL/bin/sshping
      craftctl default
    
  sshping-wrapper:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp $SNAPCRAFT_PART_SRC/snap/sshping-wrapper $SNAPCRAFT_PART_INSTALL/bin/sshping-wrapper
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/sshping-wrapper

apps:
  sshping:
    command: bin/sshping-wrapper
    plugs:
      - network
      - network-bind
      - ssh-keys
